version: '3.8'

services:
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - labs

  auth-service:
    image: serfanrud/${RELEASE_AUTH_SERVICE}
    container_name: auth-service
    hostname: auth-service
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - ${labs:labs}